-- ==========================================================
-- Universidad - Spring Boot MVC
-- Script DDL de creación de tablas
-- Motor de base de datos: PostgreSQL
-- Base de datos objetivo: 7502523005_2_Universidad
-- ==========================================================

SET client_encoding = 'UTF8';

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id      VARCHAR(255) NOT NULL,
    clave   VARCHAR(255) NOT NULL,
    nombre  VARCHAR(255) NOT NULL,
    rol     VARCHAR(255) NOT NULL,
    email   VARCHAR(255),
    CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios (LOWER(rol));

-- 2. Tabla de Universidades
CREATE TABLE IF NOT EXISTS universidades (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(255) NOT NULL,
    categoria        VARCHAR(255) NOT NULL,
    web              VARCHAR(255) NOT NULL,
    rector           VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    acceso           VARCHAR(255) NOT NULL,
    telefono         VARCHAR(255) NOT NULL,
    ciudad           VARCHAR(255) NOT NULL,
    numero_carreras  INTEGER NOT NULL,
    num_sedes        INTEGER NOT NULL,
    CONSTRAINT universidad_pkey PRIMARY KEY (id),
    CONSTRAINT universidad_nombre_key UNIQUE (nombre)
);

CREATE INDEX IF NOT EXISTS idx_universidades_ciudad ON universidades (LOWER(ciudad));
CREATE INDEX IF NOT EXISTS idx_universidades_categoria ON universidades (LOWER(categoria));

-- 3. Tabla de Tokens de Recuperación de Clave
CREATE TABLE IF NOT EXISTS tokens_recuperacion (
    token             VARCHAR(255) NOT NULL,
    usuario_id        VARCHAR(255) NOT NULL,
    fecha_expiracion  TIMESTAMP NOT NULL,
    CONSTRAINT tokens_recuperacion_pkey PRIMARY KEY (token)
);
