-- ============================================================
-- Script de creación de la tabla "universidades" (PostgreSQL)
-- Entidad: com.universidad.modelo.Universidad
-- ============================================================

CREATE TABLE IF NOT EXISTS universidades (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(255) NOT NULL,
    categoria        VARCHAR(255) NOT NULL,
    web              VARCHAR(255) NOT NULL,
    rector           VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    acceso           VARCHAR(255) NOT NULL,
    telefono         VARCHAR(255) NOT NULL,
    ciudad           VARCHAR(255) NOT NULL,
    numero_carreras  INTEGER NOT NULL,
    num_sedes        INTEGER NOT NULL,
    CONSTRAINT universidad_pkey PRIMARY KEY (id),
    CONSTRAINT universidad_nombre_key UNIQUE (nombre)
);

CREATE INDEX IF NOT EXISTS idx_universidades_ciudad ON universidades (lower(ciudad));
CREATE INDEX IF NOT EXISTS idx_universidades_categoria ON universidades (lower(categoria));

-- ============================================================
-- Datos iniciales (seed)
-- ============================================================

INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (102, 'Universidad Nacional de Colombia', 'Pública', 'https://unal.edu.co', 'Leopoldo Múnera Ruiz', 'contacto@unal.edu.co', 'Examen de Admisión', '6013165000', 'Bogotá', 94, 9);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (103, 'Universidad de Antioquia', 'Pública', 'https://udea.edu.co', 'John Jairo Arboleda', 'info@udea.edu.co', 'Examen de Admisión', '6042198332', 'Medellín', 82, 12);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (104, 'Universidad del Valle', 'Pública', 'https://univalle.edu.co', 'Guillermo Murillo Vargas', 'rectoria@univalle.edu.co', 'Pruebas Saber 11 / ICFES', '6023212100', 'Cali', 65, 8);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (105, 'Pontificia Universidad Javeriana', 'Privada', 'https://javeriana.edu.co', 'Luis Fernando Múnera', 'contacto@javeriana.edu.co', 'Ingreso Directo', '6013208320', 'Bogotá', 45, 2);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (106, 'Universidad del Norte', 'Privada', 'https://uninorte.edu.co', 'Adolfo Meisel Roca', 'info@uninorte.edu.co', 'Pruebas Saber 11 / ICFES', '6053509509', 'Barranquilla', 38, 1);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (107, 'Universidad Industrial de Santander', 'Pública', 'https://uis.edu.co', 'Hernán Porras Díaz', 'contacto@uis.edu.co', 'Pruebas Saber 11 / ICFES', '6076344000', 'Bucaramanga', 52, 5);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (108, 'Universidad de Caldas', 'Pública', 'https://ucaldas.edu.co', 'Fabio Hernando Arias', 'atencion@ucaldas.edu.co', 'Pruebas Saber 11 / ICFES', '6068781500', 'Manizales', 35, 4);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (109, 'Universidad del Cauca', 'Pública', 'https://unicauca.edu.co', 'Deibar René Hurtado', 'prensa@unicauca.edu.co', 'Examen de Admisión', '6028209800', 'Popayán', 42, 3);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (110, 'Universidad Tecnológica de Pereira', 'Pública', 'https://utp.edu.co', 'Luis Fernando Gaviria', 'contacto@utp.edu.co', 'Pruebas Saber 11 / ICFES', '6063137300', 'Pereira', 36, 2);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (111, 'Universidad del Magdalena', 'Pública', 'https://unimagdalena.edu.co', 'Pablo Vera Salazar', 'info@unimagdalena.edu.co', 'Examen de Admisión', '6054381000', 'Santa Marta', 32, 1);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (112, 'Universidad de los Andes', 'Privada', 'https://uniandes.edu.co', 'Raquel Bernal Salazar', 'contacto@uniandes.edu.co', 'Pruebas Saber 11 / ICFES', '6013394949', 'Bogotá', 43, 2);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (113, 'Universidad EAFIT', 'Privada', 'https://eafit.edu.co', 'Claudia Restrepo Montoya', 'contacto@eafit.edu.co', 'Ingreso Directo', '6042619500', 'Medellín', 28, 4);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (114, 'Universidad Icesi', 'Privada', 'https://icesi.edu.co', 'Esteban Piedrahita', 'info@icesi.edu.co', 'Pruebas Saber 11 / ICFES', '6025552334', 'Cali', 30, 1);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (115, 'Universidad de La Sabana', 'Privada', 'https://unisabana.edu.co', 'Rolando Roncancio', 'atencion@unisabana.edu.co', 'Pruebas Saber 11 / ICFES', '6018615555', 'Chía', 26, 1);
INSERT INTO universidades (id, nombre, categoria, web, rector, email, acceso, telefono, ciudad, numero_carreras, num_sedes) VALUES (116, 'Universidad Pontificia Bolivariana', 'Privada', 'https://upb.edu.co', 'Diego Alonso Marulanda', 'asesoria@upb.edu.co', 'Ingreso Directo', '6044488388', 'Medellín', 37, 5);

-- Continúa el autoincremento de "id" después de la última fila semilla
SELECT setval(pg_get_serial_sequence('universidades', 'id'), 117, false);
