spring.application.name=Universidad - Spring Boot
spring.thymeleaf.cache=false
server.port=8085

# Conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/7502523005_2_Universidad
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true